// client/src/views/Login.svelte
<script lang="ts">
  import { user } from "../services/stores";

  let userValue = "";

  const onSubmit = () => {
    user.set(userValue);
  };
</script>

<h3>Welcome!</h3>
<p>How should your chatmates call you?</p>

<form on:submit|preventDefault={onSubmit}>
  <label for="user">Username</label>
  <input
    type="text"
    name="user"
    bind:value={userValue}
    placeholder="Enter your username..."
    required
  />
  <button type="submit">Enter chat</button>
</form>

// client/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { UserService } from '../shared';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  userName: string;

  constructor(
    private userService: UserService,
    private router: Router,
  ) { }

  ngOnInit() {
  }

  enterChat() {
    this.userService.set(this.userName);
    this.router.navigate([this.userService.redirectUrl || '/']);
  }

}

<div class="container">
  <form class="login-form" (ngSubmit)="f.valid && enterChat()" #f="ngForm">
    <h1>Chat Room</h1>
    <h3>Welcome.</h3>
    <p>
      How should your chatmates call you?
    </p>
    <input type="text" name="userName" [(ngModel)]="userName" placeholder="Enter your username..." required>
  </form>
</div>
